# Generated by Django 2.2.2 on 2019-06-11 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified_at')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'shopping list',
                'verbose_name_plural': 'shopping lists',
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified_at')),
                ('description', models.CharField(max_length=256, verbose_name='description')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to='shoppinglist.ShoppingList')),
            ],
            options={
                'verbose_name': 'shopping item',
                'verbose_name_plural': 'shopping items',
            },
        ),
    ]
