# Generated by Django 2.2.2 on 2019-06-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='done',
            field=models.BooleanField(default=False, verbose_name='done'),
        ),
    ]
