# Generated by Django 2.2.2 on 2019-06-23 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoppinglist', '0003_shoppinglist_is_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='co_authors',
            field=models.ManyToManyField(related_name='co_authored_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
